#print('Qual o seu nome?')
nome = input('Qual o seu nome? ')
#print('Seja bem vindo(a) %s' % nome)
#print('Seja bem vindo(a) {0}'.format(nome))
print(f'Seja bem vindo(a) {nome}')
#print('Qual sua idade?')
idade = int(input('Qualdo a sua idade? '))
#print('A %s tem %s anos.' %(nome, idade))
#print('A {0} tem {1} anos'.format(nome,idade))
print(f'A {nome} tem {idade} anos')
#print(f'A {nome} nasceu em {2024-int(idade)}')
print(f'A {nome} nasceu em {2024-idade}')
